# https://nsls-ii.github.io/scientific-python-cookiecutter/pre-commit.html#configuring-pre-commit
repos:
  - repo: https://github.com/ambv/black
    rev: 23.10.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
        args:
        - --ignore=E501  # line too long
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout